A = "asset"
E = "expense"
L = "liability"
OE = "owner's equity"

MAIN = "main"
SECOND = "2nd"
THIRD = "3rd"

CR = "cr"
DR = "dr"

POS = "positive"
NEG = "negative"

CASH = "cash"
AR = "accounts receivable"
INV = "inventory"
SUPPLY = "supplies"
PRE_EXP = "prepaid expenses"
LAND = "land"
BUILD = "buildings"
EQUIP = "equipment"
GOODWILL = "goodwill"
AP = "accounts payable"
NOTE_P = "notes payable"
SALA_P = "salaries payable"
SALA_EXP = "salaries expense"
RENT_EXP = "rent expense"
WAG_P = "wages payable"
WAG_EXP = "wages expense"
INT_P = "interest payable"
I_TAX_P = "income taxes payable"
UR = "unearned revenue"
REV = "revenue"
COGS = "cost of goods sold"
INT_INVST = "initial investment"


MERCHANT_INV = "merchandise inventory"